DROP TABLE IF EXISTS audit_trail CASCADE;

DROP TABLE IF EXISTS contracts CASCADE;

DROP TABLE IF EXISTS compliance_records CASCADE;

DROP TABLE IF EXISTS risk_assessments CASCADE;

DROP TABLE IF EXISTS vendor_contacts CASCADE;

DROP TABLE IF EXISTS vendors CASCADE;

DROP TABLE IF EXISTS users CASCADE;

DROP EXTENSION IF EXISTS "pgcrypto";