// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type AuditTrail struct {
	ID         string    `json:"id"`
	Code       string    `json:"code"`
	TableName  string    `json:"tableName"`
	RecordID   string    `json:"recordId"`
	RecordCode *string   `json:"recordCode,omitempty"`
	Action     string    `json:"action"`
	FieldName  *string   `json:"fieldName,omitempty"`
	OldValue   *string   `json:"oldValue,omitempty"`
	NewValue   *string   `json:"newValue,omitempty"`
	ChangedBy  string    `json:"changedBy"`
	ChangedAt  time.Time `json:"changedAt"`
}

type Category struct {
	ID          string         `json:"id"`
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	DisplayName string         `json:"displayName"`
	Description *string        `json:"description,omitempty"`
	Status      CategoryStatus `json:"status"`
	CreatedBy   *string        `json:"createdBy,omitempty"`
	UpdatedBy   *string        `json:"updatedBy,omitempty"`
	CreatedAt   time.Time      `json:"createdAt"`
	UpdatedAt   time.Time      `json:"updatedAt"`
}

type CategoryList struct {
	Data  []*Category `json:"data"`
	Total int         `json:"total"`
}

type ComplianceRecord struct {
	ID                string            `json:"id"`
	Code              string            `json:"code"`
	VendorID          string            `json:"vendorId"`
	VendorCode        *string           `json:"vendorCode,omitempty"`
	CertificationType CertificationType `json:"certificationType"`
	Status            ComplianceStatus  `json:"status"`
	ValidFrom         *time.Time        `json:"validFrom,omitempty"`
	ValidUntil        *time.Time        `json:"validUntil,omitempty"`
	IssuedBy          *string           `json:"issuedBy,omitempty"`
	EvidenceURL       *string           `json:"evidenceUrl,omitempty"`
	ReviewedBy        *string           `json:"reviewedBy,omitempty"`
	CreatedAt         time.Time         `json:"createdAt"`
	UpdatedAt         time.Time         `json:"updatedAt"`
}

type ComplianceSummaryItem struct {
	CertificationType string `json:"certificationType"`
	Approved          int    `json:"approved"`
	Pending           int    `json:"pending"`
	Expired           int    `json:"expired"`
	Total             int    `json:"total"`
}

type Contract struct {
	ID             string        `json:"id"`
	Code           string        `json:"code"`
	VendorID       string        `json:"vendorId"`
	VendorCode     *string       `json:"vendorCode,omitempty"`
	ContractNumber string        `json:"contractNumber"`
	StartDate      time.Time     `json:"startDate"`
	EndDate        time.Time     `json:"endDate"`
	ContractValue  *float64      `json:"contractValue,omitempty"`
	RenewalStatus  RenewalStatus `json:"renewalStatus"`
	CreatedAt      time.Time     `json:"createdAt"`
	UpdatedAt      time.Time     `json:"updatedAt"`
}

type CreateCategoryInput struct {
	Name        string         `json:"name"`
	DisplayName string         `json:"displayName"`
	Description *string        `json:"description,omitempty"`
	Status      CategoryStatus `json:"status"`
}

type CreateComplianceInput struct {
	VendorCode        string            `json:"vendorCode"`
	CertificationType CertificationType `json:"certificationType"`
	ValidFrom         *time.Time        `json:"validFrom,omitempty"`
	ValidUntil        *time.Time        `json:"validUntil,omitempty"`
	IssuedBy          *string           `json:"issuedBy,omitempty"`
	EvidenceURL       *string           `json:"evidenceUrl,omitempty"`
}

type CreateContactInput struct {
	Name  string  `json:"name"`
	Email *string `json:"email,omitempty"`
	Phone *string `json:"phone,omitempty"`
}

type CreateContractInput struct {
	VendorCode     string        `json:"vendorCode"`
	ContractNumber string        `json:"contractNumber"`
	StartDate      time.Time     `json:"startDate"`
	EndDate        time.Time     `json:"endDate"`
	ContractValue  *float64      `json:"contractValue,omitempty"`
	RenewalStatus  RenewalStatus `json:"renewalStatus"`
}

type CreateRiskAssessmentInput struct {
	VendorCode           string    `json:"vendorCode"`
	AssessmentDate       time.Time `json:"assessmentDate"`
	OverallRiskScore     float64   `json:"overallRiskScore"`
	RiskLevel            RiskLevel `json:"riskLevel"`
	SecurityRiskScore    float64   `json:"securityRiskScore"`
	FinancialRiskScore   float64   `json:"financialRiskScore"`
	OperationalRiskScore float64   `json:"operationalRiskScore"`
	LegalRiskScore       float64   `json:"legalRiskScore"`
	Notes                *string   `json:"notes,omitempty"`
}

type CreateUserInput struct {
	Email    string   `json:"email"`
	Password string   `json:"password"`
	FullName string   `json:"fullName"`
	Role     UserRole `json:"role"`
}

type CreateVendorInput struct {
	Name          string    `json:"name"`
	Category      string    `json:"category"`
	ContactPerson *string   `json:"contactPerson,omitempty"`
	ContactEmail  *string   `json:"contactEmail,omitempty"`
	Country       *string   `json:"country,omitempty"`
	RiskLevel     RiskLevel `json:"riskLevel"`
}

type ExpiringContract struct {
	Code           string   `json:"code"`
	VendorName     string   `json:"vendorName"`
	VendorCode     string   `json:"vendorCode"`
	ContractNumber string   `json:"contractNumber"`
	EndDate        string   `json:"endDate"`
	DaysRemaining  int      `json:"daysRemaining"`
	RenewalStatus  string   `json:"renewalStatus"`
	ContractValue  *float64 `json:"contractValue,omitempty"`
}

type HighRiskVendor struct {
	Code                string   `json:"code"`
	Name                string   `json:"name"`
	Category            string   `json:"category"`
	RiskLevel           string   `json:"riskLevel"`
	OverallRiskScore    *float64 `json:"overallRiskScore,omitempty"`
	LatestAssessment    *string  `json:"latestAssessment,omitempty"`
	AssessmentStatus    *string  `json:"assessmentStatus,omitempty"`
	ExpiringContracts30 *int     `json:"expiringContracts30,omitempty"`
}

type KeyValue struct {
	Key   string `json:"key"`
	Value int    `json:"value"`
}

type LoginResponse struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type MonthlyOnboarding struct {
	Month string `json:"month"`
	Count int    `json:"count"`
}

type Mutation struct {
}

type Query struct {
}

type RiskAssessment struct {
	ID                   string           `json:"id"`
	Code                 string           `json:"code"`
	VendorID             string           `json:"vendorId"`
	VendorCode           *string          `json:"vendorCode,omitempty"`
	AssessmentDate       time.Time        `json:"assessmentDate"`
	AssessorID           *string          `json:"assessorId,omitempty"`
	OverallRiskScore     float64          `json:"overallRiskScore"`
	RiskLevel            RiskLevel        `json:"riskLevel"`
	SecurityRiskScore    float64          `json:"securityRiskScore"`
	FinancialRiskScore   float64          `json:"financialRiskScore"`
	OperationalRiskScore float64          `json:"operationalRiskScore"`
	LegalRiskScore       float64          `json:"legalRiskScore"`
	Status               AssessmentStatus `json:"status"`
	Notes                *string          `json:"notes,omitempty"`
	CreatedAt            time.Time        `json:"createdAt"`
	UpdatedAt            time.Time        `json:"updatedAt"`
}

type SummaryReport struct {
	TotalVendors            int         `json:"totalVendors"`
	VendorsByStatus         []*KeyValue `json:"vendorsByStatus"`
	VendorsByRiskLevel      []*KeyValue `json:"vendorsByRiskLevel"`
	ExpiringContracts30     int         `json:"expiringContracts30"`
	ExpiringContracts60     int         `json:"expiringContracts60"`
	ExpiringContracts90     int         `json:"expiringContracts90"`
	ExpiringCompliance30    int         `json:"expiringCompliance30"`
	ExpiringCompliance60    int         `json:"expiringCompliance60"`
	ExpiringCompliance90    int         `json:"expiringCompliance90"`
	PendingRiskAssessments  int         `json:"pendingRiskAssessments"`
	ApprovedRiskAssessments int         `json:"approvedRiskAssessments"`
}

type TimeSeries struct {
	Vendors         []*TimeSeriesPoint `json:"vendors"`
	RiskAssessments []*TimeSeriesPoint `json:"riskAssessments"`
	Compliance      []*TimeSeriesPoint `json:"compliance"`
}

type TimeSeriesPoint struct {
	Date  string `json:"date"`
	Count int    `json:"count"`
}

type UpdateCategoryInput struct {
	DisplayName string         `json:"displayName"`
	Description *string        `json:"description,omitempty"`
	Status      CategoryStatus `json:"status"`
}

type UpdateComplianceInput struct {
	CertificationType CertificationType `json:"certificationType"`
	Status            ComplianceStatus  `json:"status"`
	ValidFrom         *time.Time        `json:"validFrom,omitempty"`
	ValidUntil        *time.Time        `json:"validUntil,omitempty"`
	IssuedBy          *string           `json:"issuedBy,omitempty"`
	EvidenceURL       *string           `json:"evidenceUrl,omitempty"`
}

type UpdateContactInput struct {
	Name  string  `json:"name"`
	Email *string `json:"email,omitempty"`
	Phone *string `json:"phone,omitempty"`
}

type UpdateContractInput struct {
	VendorCode     string        `json:"vendorCode"`
	ContractNumber string        `json:"contractNumber"`
	StartDate      time.Time     `json:"startDate"`
	EndDate        time.Time     `json:"endDate"`
	ContractValue  *float64      `json:"contractValue,omitempty"`
	RenewalStatus  RenewalStatus `json:"renewalStatus"`
}

type UpdateRiskAssessmentInput struct {
	AssessmentDate       time.Time        `json:"assessmentDate"`
	OverallRiskScore     float64          `json:"overallRiskScore"`
	RiskLevel            RiskLevel        `json:"riskLevel"`
	SecurityRiskScore    float64          `json:"securityRiskScore"`
	FinancialRiskScore   float64          `json:"financialRiskScore"`
	OperationalRiskScore float64          `json:"operationalRiskScore"`
	LegalRiskScore       float64          `json:"legalRiskScore"`
	Status               AssessmentStatus `json:"status"`
	Notes                *string          `json:"notes,omitempty"`
}

type UpdateRoleInput struct {
	Role UserRole `json:"role"`
}

type UpdateVendorInput struct {
	Name          string       `json:"name"`
	Category      string       `json:"category"`
	ContactPerson *string      `json:"contactPerson,omitempty"`
	ContactEmail  *string      `json:"contactEmail,omitempty"`
	Country       *string      `json:"country,omitempty"`
	RiskLevel     RiskLevel    `json:"riskLevel"`
	Status        VendorStatus `json:"status"`
}

type User struct {
	ID        string    `json:"id"`
	Code      string    `json:"code"`
	Email     string    `json:"email"`
	FullName  string    `json:"fullName"`
	Role      UserRole  `json:"role"`
	IsActive  bool      `json:"isActive"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type Vendor struct {
	ID                    string              `json:"id"`
	Code                  string              `json:"code"`
	Name                  string              `json:"name"`
	Category              string              `json:"category"`
	ContactPerson         *string             `json:"contactPerson,omitempty"`
	ContactEmail          *string             `json:"contactEmail,omitempty"`
	Country               *string             `json:"country,omitempty"`
	RiskLevel             RiskLevel           `json:"riskLevel"`
	Status                VendorStatus        `json:"status"`
	AssignedDeptManagerID *string             `json:"assignedDeptManagerID,omitempty"`
	CreatedBy             string              `json:"createdBy"`
	CreatedAt             time.Time           `json:"createdAt"`
	UpdatedAt             time.Time           `json:"updatedAt"`
	Contacts              []*VendorContact    `json:"contacts"`
	RiskAssessments       []*RiskAssessment   `json:"riskAssessments"`
	ComplianceRecords     []*ComplianceRecord `json:"complianceRecords"`
	Contracts             []*Contract         `json:"contracts"`
}

type VendorContact struct {
	ID        string    `json:"id"`
	Code      string    `json:"code"`
	VendorID  string    `json:"vendorId"`
	Name      string    `json:"name"`
	Email     *string   `json:"email,omitempty"`
	Phone     *string   `json:"phone,omitempty"`
	CreatedAt time.Time `json:"createdAt"`
}

type VendorList struct {
	Data  []*Vendor `json:"data"`
	Total int       `json:"total"`
}

type VendorListFilter struct {
	Search    *string       `json:"search,omitempty"`
	Category  *string       `json:"category,omitempty"`
	RiskLevel *RiskLevel    `json:"riskLevel,omitempty"`
	Status    *VendorStatus `json:"status,omitempty"`
	Country   *string       `json:"country,omitempty"`
	CreatedBy *string       `json:"createdBy,omitempty"`
}

type AssessmentStatus string

const (
	AssessmentStatusDraft    AssessmentStatus = "Draft"
	AssessmentStatusReviewed AssessmentStatus = "Reviewed"
	AssessmentStatusApproved AssessmentStatus = "Approved"
)

var AllAssessmentStatus = []AssessmentStatus{
	AssessmentStatusDraft,
	AssessmentStatusReviewed,
	AssessmentStatusApproved,
}

func (e AssessmentStatus) IsValid() bool {
	switch e {
	case AssessmentStatusDraft, AssessmentStatusReviewed, AssessmentStatusApproved:
		return true
	}
	return false
}

func (e AssessmentStatus) String() string {
	return string(e)
}

func (e *AssessmentStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AssessmentStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AssessmentStatus", str)
	}
	return nil
}

func (e AssessmentStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AssessmentStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AssessmentStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CategoryStatus string

const (
	CategoryStatusDraft    CategoryStatus = "Draft"
	CategoryStatusActive   CategoryStatus = "Active"
	CategoryStatusInactive CategoryStatus = "Inactive"
)

var AllCategoryStatus = []CategoryStatus{
	CategoryStatusDraft,
	CategoryStatusActive,
	CategoryStatusInactive,
}

func (e CategoryStatus) IsValid() bool {
	switch e {
	case CategoryStatusDraft, CategoryStatusActive, CategoryStatusInactive:
		return true
	}
	return false
}

func (e CategoryStatus) String() string {
	return string(e)
}

func (e *CategoryStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CategoryStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CategoryStatus", str)
	}
	return nil
}

func (e CategoryStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CategoryStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CategoryStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CertificationType string

const (
	CertificationTypeIso27001 CertificationType = "ISO27001"
	CertificationTypeSoc2     CertificationType = "SOC2"
	CertificationTypeGdpr     CertificationType = "GDPR"
	CertificationTypePciDss   CertificationType = "PCI_DSS"
)

var AllCertificationType = []CertificationType{
	CertificationTypeIso27001,
	CertificationTypeSoc2,
	CertificationTypeGdpr,
	CertificationTypePciDss,
}

func (e CertificationType) IsValid() bool {
	switch e {
	case CertificationTypeIso27001, CertificationTypeSoc2, CertificationTypeGdpr, CertificationTypePciDss:
		return true
	}
	return false
}

func (e CertificationType) String() string {
	return string(e)
}

func (e *CertificationType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CertificationType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CertificationType", str)
	}
	return nil
}

func (e CertificationType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CertificationType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CertificationType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ComplianceStatus string

const (
	ComplianceStatusPending  ComplianceStatus = "Pending"
	ComplianceStatusApproved ComplianceStatus = "Approved"
	ComplianceStatusExpired  ComplianceStatus = "Expired"
)

var AllComplianceStatus = []ComplianceStatus{
	ComplianceStatusPending,
	ComplianceStatusApproved,
	ComplianceStatusExpired,
}

func (e ComplianceStatus) IsValid() bool {
	switch e {
	case ComplianceStatusPending, ComplianceStatusApproved, ComplianceStatusExpired:
		return true
	}
	return false
}

func (e ComplianceStatus) String() string {
	return string(e)
}

func (e *ComplianceStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ComplianceStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ComplianceStatus", str)
	}
	return nil
}

func (e ComplianceStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ComplianceStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ComplianceStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RenewalStatus string

const (
	RenewalStatusAutoRenew RenewalStatus = "Auto_Renew"
	RenewalStatusManual    RenewalStatus = "Manual"
	RenewalStatusExpiring  RenewalStatus = "Expiring"
)

var AllRenewalStatus = []RenewalStatus{
	RenewalStatusAutoRenew,
	RenewalStatusManual,
	RenewalStatusExpiring,
}

func (e RenewalStatus) IsValid() bool {
	switch e {
	case RenewalStatusAutoRenew, RenewalStatusManual, RenewalStatusExpiring:
		return true
	}
	return false
}

func (e RenewalStatus) String() string {
	return string(e)
}

func (e *RenewalStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RenewalStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RenewalStatus", str)
	}
	return nil
}

func (e RenewalStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RenewalStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RenewalStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RiskLevel string

const (
	RiskLevelLow      RiskLevel = "Low"
	RiskLevelMedium   RiskLevel = "Medium"
	RiskLevelHigh     RiskLevel = "High"
	RiskLevelCritical RiskLevel = "Critical"
)

var AllRiskLevel = []RiskLevel{
	RiskLevelLow,
	RiskLevelMedium,
	RiskLevelHigh,
	RiskLevelCritical,
}

func (e RiskLevel) IsValid() bool {
	switch e {
	case RiskLevelLow, RiskLevelMedium, RiskLevelHigh, RiskLevelCritical:
		return true
	}
	return false
}

func (e RiskLevel) String() string {
	return string(e)
}

func (e *RiskLevel) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RiskLevel(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RiskLevel", str)
	}
	return nil
}

func (e RiskLevel) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RiskLevel) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RiskLevel) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type UserRole string

const (
	UserRoleSystemAdmin       UserRole = "system_admin"
	UserRoleRiskManager       UserRole = "risk_manager"
	UserRoleComplianceOfficer UserRole = "compliance_officer"
	UserRoleDepartmentManager UserRole = "department_manager"
	UserRoleAuditor           UserRole = "auditor"
)

var AllUserRole = []UserRole{
	UserRoleSystemAdmin,
	UserRoleRiskManager,
	UserRoleComplianceOfficer,
	UserRoleDepartmentManager,
	UserRoleAuditor,
}

func (e UserRole) IsValid() bool {
	switch e {
	case UserRoleSystemAdmin, UserRoleRiskManager, UserRoleComplianceOfficer, UserRoleDepartmentManager, UserRoleAuditor:
		return true
	}
	return false
}

func (e UserRole) String() string {
	return string(e)
}

func (e *UserRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserRole", str)
	}
	return nil
}

func (e UserRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UserRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UserRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type VendorStatus string

const (
	VendorStatusDraft            VendorStatus = "Draft"
	VendorStatusSubmitted        VendorStatus = "Submitted"
	VendorStatusRiskReview       VendorStatus = "RiskReview"
	VendorStatusComplianceReview VendorStatus = "ComplianceReview"
	VendorStatusApproved         VendorStatus = "Approved"
	VendorStatusRejected         VendorStatus = "Rejected"
	VendorStatusActive           VendorStatus = "Active"
	VendorStatusInactive         VendorStatus = "Inactive"
)

var AllVendorStatus = []VendorStatus{
	VendorStatusDraft,
	VendorStatusSubmitted,
	VendorStatusRiskReview,
	VendorStatusComplianceReview,
	VendorStatusApproved,
	VendorStatusRejected,
	VendorStatusActive,
	VendorStatusInactive,
}

func (e VendorStatus) IsValid() bool {
	switch e {
	case VendorStatusDraft, VendorStatusSubmitted, VendorStatusRiskReview, VendorStatusComplianceReview, VendorStatusApproved, VendorStatusRejected, VendorStatusActive, VendorStatusInactive:
		return true
	}
	return false
}

func (e VendorStatus) String() string {
	return string(e)
}

func (e *VendorStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = VendorStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid VendorStatus", str)
	}
	return nil
}

func (e VendorStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *VendorStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e VendorStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
