package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.92

import (
	"context"
	"fmt"

	"github.com/uswuth/vytora-backend/internal/graphql/model"
)

// AuditTrails is the resolver for the auditTrails field.
func (r *queryResolver) AuditTrails(ctx context.Context, tableName *string, recordCode *string, action *string, changedBy *string, dateFrom *string, dateTo *string, limit *int, offset *int) ([]*model.AuditTrail, error) {
	panic(fmt.Errorf("not implemented: AuditTrails - auditTrails"))
}
