package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.92

import (
	"context"

	"github.com/google/uuid"
	"github.com/uswuth/vytora-backend/internal/entity/category"
	"github.com/uswuth/vytora-backend/internal/graphql/model"
)

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, input model.CreateCategoryInput) (*model.Category, error) {
	code, err := r.SeqService.NextCode(ctx, "category")
	if err != nil {
		return nil, err
	}
	claims, _ := GetClaims(ctx)
	createdBy, _ := uuid.Parse(claims.UserID)

	cat := &category.Category{
		Code:        code,
		Name:        input.Name,
		DisplayName: input.DisplayName,
		Status:      string(input.Status),
		CreatedBy:   &createdBy,
	}
	if input.Description != nil {
		cat.Description = *input.Description
	}
	if err := r.CategoryRepo.Create(ctx, cat); err != nil {
		return nil, err
	}
	return mapCategoryToGraphQL(cat), nil
}

// UpdateCategory is the resolver for the updateCategory field.
func (r *mutationResolver) UpdateCategory(ctx context.Context, code string, input model.UpdateCategoryInput) (*model.Category, error) {
	cat, err := r.CategoryRepo.FindByCode(ctx, code)
	if err != nil {
		return nil, &NotFoundError{Resource: "category"}
	}
	claims, _ := GetClaims(ctx)
	updatedBy, _ := uuid.Parse(claims.UserID)

	cat.DisplayName = input.DisplayName
	cat.Status = string(input.Status)
	cat.UpdatedBy = &updatedBy
	if input.Description != nil {
		cat.Description = *input.Description
	}
	if err := r.CategoryRepo.Update(ctx, cat); err != nil {
		return nil, err
	}
	return mapCategoryToGraphQL(cat), nil
}

// DeleteCategory is the resolver for the deleteCategory field.
func (r *mutationResolver) DeleteCategory(ctx context.Context, code string) (bool, error) {
	if err := r.CategoryRepo.Delete(ctx, code); err != nil {
		return false, err
	}
	return true, nil
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context, search *string, status *model.CategoryStatus, limit *int, offset *int) (*model.CategoryList, error) {
	params := category.ListParams{}
	if search != nil {
		params.Search = *search
	}
	if status != nil {
		params.Status = string(*status)
	}
	if limit != nil {
		params.Limit = *limit
	}
	if offset != nil {
		params.Offset = *offset
	}
	cats, total, err := r.CategoryRepo.List(ctx, params)
	if err != nil {
		return nil, err
	}
	gqlCats := make([]*model.Category, len(cats))
	for i, c := range cats {
		gqlCats[i] = mapCategoryToGraphQL(&c)
	}
	return &model.CategoryList{Data: gqlCats, Total: total}, nil
}

// Category is the resolver for the category field.
func (r *queryResolver) Category(ctx context.Context, code string) (*model.Category, error) {
	cat, err := r.CategoryRepo.FindByCode(ctx, code)
	if err != nil {
		return nil, &NotFoundError{Resource: "category"}
	}
	return mapCategoryToGraphQL(cat), nil
}
