package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.92

import (
	"context"

	"github.com/google/uuid"
	"github.com/uswuth/vytora-backend/internal/entity/compliance_record"
	"github.com/uswuth/vytora-backend/internal/graphql/model"
)

// CreateComplianceRecord is the resolver for the createComplianceRecord field.
func (r *mutationResolver) CreateComplianceRecord(ctx context.Context, input model.CreateComplianceInput) (*model.ComplianceRecord, error) {
	v, err := r.VendorRepo.FindByCode(ctx, input.VendorCode)
	if err != nil {
		return nil, &NotFoundError{Resource: "vendor"}
	}
	code, err := r.SeqService.NextCode(ctx, "compliance_record")
	if err != nil {
		return nil, err
	}
	claims, _ := GetClaims(ctx)
	reviewedBy, _ := uuid.Parse(claims.UserID)

	cr := &compliance_record.ComplianceRecord{
		Code:              code,
		VendorID:          v.ID,
		VendorCode:        v.Code,
		CertificationType: string(input.CertificationType),
		Status:            "Pending",
		IssuedBy:          derefString(input.IssuedBy),
		EvidenceURL:       derefString(input.EvidenceURL),
		ReviewedBy:        &reviewedBy,
	}
	if input.ValidFrom != nil {
		cr.ValidFrom = input.ValidFrom
	}
	if input.ValidUntil != nil {
		cr.ValidUntil = input.ValidUntil
	}
	if err := r.ComplianceRepo.Create(ctx, cr); err != nil {
		return nil, err
	}
	_ = r.AuditLogger.LogCreateSimple(ctx, "compliance_records", cr.ID, cr.Code, reviewedBy)
	return mapComplianceRecordToGraphQL(cr), nil
}

// UpdateComplianceRecord is the resolver for the updateComplianceRecord field.
func (r *mutationResolver) UpdateComplianceRecord(ctx context.Context, code string, input model.UpdateComplianceInput) (*model.ComplianceRecord, error) {
	cr, err := r.ComplianceRepo.FindByCode(ctx, code)
	if err != nil {
		return nil, &NotFoundError{Resource: "compliance record"}
	}
	claims, _ := GetClaims(ctx)
	reviewedBy, _ := uuid.Parse(claims.UserID)

	cr.CertificationType = string(input.CertificationType)
	cr.Status = string(input.Status)
	cr.IssuedBy = derefString(input.IssuedBy)
	cr.EvidenceURL = derefString(input.EvidenceURL)
	cr.ReviewedBy = &reviewedBy
	if input.ValidFrom != nil {
		cr.ValidFrom = input.ValidFrom
	}
	if input.ValidUntil != nil {
		cr.ValidUntil = input.ValidUntil
	}

	if err := r.ComplianceRepo.Update(ctx, cr); err != nil {
		return nil, err
	}
	_ = r.AuditLogger.LogCreateSimple(ctx, "compliance_records", cr.ID, cr.Code, reviewedBy)
	return mapComplianceRecordToGraphQL(cr), nil
}

// DeleteComplianceRecord is the resolver for the deleteComplianceRecord field.
func (r *mutationResolver) DeleteComplianceRecord(ctx context.Context, code string) (bool, error) {
	cr, err := r.ComplianceRepo.FindByCode(ctx, code)
	if err != nil {
		return false, &NotFoundError{Resource: "compliance record"}
	}
	if err := r.ComplianceRepo.Delete(ctx, code); err != nil {
		return false, err
	}
	claims, _ := GetClaims(ctx)
	changedBy, _ := uuid.Parse(claims.UserID)
	_ = r.AuditLogger.LogDeleteSimple(ctx, "compliance_records", cr.ID, cr.Code, changedBy)
	return true, nil
}

// ComplianceRecords is the resolver for the complianceRecords field.
func (r *queryResolver) ComplianceRecords(ctx context.Context, vendorCode string) ([]*model.ComplianceRecord, error) {
	v, err := r.VendorRepo.FindByCode(ctx, vendorCode)
	if err != nil {
		return nil, &NotFoundError{Resource: "vendor"}
	}
	records, err := r.ComplianceRepo.ListByVendor(ctx, v.ID.String())
	if err != nil {
		return nil, err
	}
	result := make([]*model.ComplianceRecord, len(records))
	for i, rec := range records {
		result[i] = mapComplianceRecordToGraphQL(&rec)
	}
	return result, nil
}

// ComplianceRecord is the resolver for the complianceRecord field.
func (r *queryResolver) ComplianceRecord(ctx context.Context, code string) (*model.ComplianceRecord, error) {
	rec, err := r.ComplianceRepo.FindByCode(ctx, code)
	if err != nil {
		return nil, &NotFoundError{Resource: "compliance record"}
	}
	return mapComplianceRecordToGraphQL(rec), nil
}

// ExpiringCompliance is the resolver for the expiringCompliance field.
func (r *queryResolver) ExpiringCompliance(ctx context.Context, days *int) ([]*model.ComplianceRecord, error) {
	d := 30
	if days != nil {
		d = *days
	}
	records, err := r.ComplianceRepo.Expiring(ctx, d)
	if err != nil {
		return nil, err
	}
	result := make([]*model.ComplianceRecord, len(records))
	for i, rec := range records {
		result[i] = mapComplianceRecordToGraphQL(&rec)
	}
	return result, nil
}
