package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.92

import (
	"context"

	"github.com/google/uuid"
	"github.com/uswuth/vytora-backend/internal/entity/contract"
	"github.com/uswuth/vytora-backend/internal/graphql/model"
)

// CreateContract is the resolver for the createContract field.
func (r *mutationResolver) CreateContract(ctx context.Context, input model.CreateContractInput) (*model.Contract, error) {
	v, err := r.VendorRepo.FindByCode(ctx, input.VendorCode)
	if err != nil {
		return nil, &NotFoundError{Resource: "vendor"}
	}
	code, err := r.SeqService.NextCode(ctx, "contract")
	if err != nil {
		return nil, err
	}
	claims, _ := GetClaims(ctx)
	changedBy, _ := uuid.Parse(claims.UserID)

	contractVal := input.ContractValue
	c := &contract.Contract{
		Code:           code,
		VendorID:       v.ID,
		VendorCode:     v.Code,
		ContractNumber: input.ContractNumber,
		StartDate:      input.StartDate,
		EndDate:        input.EndDate,
		RenewalStatus:  string(input.RenewalStatus),
	}
	if contractVal != nil {
		c.ContractValue = contractVal
	}

	if err := r.ContractRepo.Create(ctx, c); err != nil {
		return nil, err
	}
	_ = r.AuditLogger.LogCreate(ctx, "contracts", c.ID, changedBy, c)
	return mapContractToGraphQL(c), nil
}

// UpdateContract is the resolver for the updateContract field.
func (r *mutationResolver) UpdateContract(ctx context.Context, code string, input model.UpdateContractInput) (*model.Contract, error) {
	c, err := r.ContractRepo.FindByCode(ctx, code)
	if err != nil {
		return nil, &NotFoundError{Resource: "contract"}
	}
	v, err := r.VendorRepo.FindByCode(ctx, input.VendorCode)
	if err != nil {
		return nil, &NotFoundError{Resource: "vendor"}
	}
	claims, _ := GetClaims(ctx)
	changedBy, _ := uuid.Parse(claims.UserID)

	c.VendorID = v.ID
	c.VendorCode = v.Code
	c.ContractNumber = input.ContractNumber
	c.StartDate = input.StartDate
	c.EndDate = input.EndDate
	c.ContractValue = input.ContractValue
	c.RenewalStatus = string(input.RenewalStatus)

	if err := r.ContractRepo.Update(ctx, c); err != nil {
		return nil, err
	}
	_ = r.AuditLogger.LogCreate(ctx, "contracts", c.ID, changedBy, c)
	return mapContractToGraphQL(c), nil
}

// DeleteContract is the resolver for the deleteContract field.
func (r *mutationResolver) DeleteContract(ctx context.Context, code string) (bool, error) {
	c, err := r.ContractRepo.FindByCode(ctx, code)
	if err != nil {
		return false, &NotFoundError{Resource: "contract"}
	}
	if err := r.ContractRepo.Delete(ctx, code); err != nil {
		return false, err
	}
	claims, _ := GetClaims(ctx)
	changedBy, _ := uuid.Parse(claims.UserID)
	_ = r.AuditLogger.LogDelete(ctx, "contracts", c.ID, c, changedBy)
	return true, nil
}

// Contracts is the resolver for the contracts field.
func (r *queryResolver) Contracts(ctx context.Context, vendorCode string) ([]*model.Contract, error) {
	v, err := r.VendorRepo.FindByCode(ctx, vendorCode)
	if err != nil {
		return nil, &NotFoundError{Resource: "vendor"}
	}
	contracts, err := r.ContractRepo.ListByVendor(ctx, v.ID.String())
	if err != nil {
		return nil, err
	}
	result := make([]*model.Contract, len(contracts))
	for i, c := range contracts {
		result[i] = mapContractToGraphQL(&c)
	}
	return result, nil
}

// Contract is the resolver for the contract field.
func (r *queryResolver) Contract(ctx context.Context, code string) (*model.Contract, error) {
	c, err := r.ContractRepo.FindByCode(ctx, code)
	if err != nil {
		return nil, &NotFoundError{Resource: "contract"}
	}
	return mapContractToGraphQL(c), nil
}

// ExpiringContracts is the resolver for the expiringContracts field.
func (r *queryResolver) ExpiringContracts(ctx context.Context, days *int) ([]*model.Contract, error) {
	d := 30
	if days != nil {
		d = *days
	}
	contracts, err := r.ContractRepo.Expiring(ctx, d)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Contract, len(contracts))
	for i, c := range contracts {
		result[i] = mapContractToGraphQL(&c)
	}
	return result, nil
}
