package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.92

import (
	"context"

	"github.com/uswuth/vytora-backend/internal/graphql/model"
)

// SummaryReport is the resolver for the summaryReport field.
func (r *queryResolver) SummaryReport(ctx context.Context) (*model.SummaryReport, error) {
	deptID := getDepartmentManagerID(ctx)
	summary, err := r.ReportRepo.GetSummary(ctx, deptID)
	if err != nil {
		return nil, err
	}
	vendorsByStatus := make([]*model.KeyValue, 0, len(summary.VendorsByStatus))
	for k, v := range summary.VendorsByStatus {
		vendorsByStatus = append(vendorsByStatus, &model.KeyValue{Key: k, Value: v})
	}
	vendorsByRisk := make([]*model.KeyValue, 0, len(summary.VendorsByRiskLevel))
	for k, v := range summary.VendorsByRiskLevel {
		vendorsByRisk = append(vendorsByRisk, &model.KeyValue{Key: k, Value: v})
	}
	return &model.SummaryReport{
		TotalVendors:            summary.TotalVendors,
		VendorsByStatus:         vendorsByStatus,
		VendorsByRiskLevel:      vendorsByRisk,
		ExpiringContracts30:     summary.ExpiringContracts30,
		ExpiringContracts60:     summary.ExpiringContracts60,
		ExpiringContracts90:     summary.ExpiringContracts90,
		ExpiringCompliance30:    summary.ExpiringCompliance30,
		ExpiringCompliance60:    summary.ExpiringCompliance60,
		ExpiringCompliance90:    summary.ExpiringCompliance90,
		PendingRiskAssessments:  summary.PendingRiskAssessments,
		ApprovedRiskAssessments: summary.ApprovedRiskAssessments,
	}, nil
}

// MonthlyOnboarding is the resolver for the monthlyOnboarding field.
func (r *queryResolver) MonthlyOnboarding(ctx context.Context) ([]*model.MonthlyOnboarding, error) {
	deptID := getDepartmentManagerID(ctx)
	data, err := r.ReportRepo.GetMonthlyOnboarding(ctx, deptID)
	if err != nil {
		return nil, err
	}
	result := make([]*model.MonthlyOnboarding, len(data))
	for i, item := range data {
		result[i] = &model.MonthlyOnboarding{Month: item.Month, Count: item.Count}
	}
	return result, nil
}

// HighRiskVendors is the resolver for the highRiskVendors field.
func (r *queryResolver) HighRiskVendors(ctx context.Context) ([]*model.HighRiskVendor, error) {
	createdBy := getDepartmentManagerID(ctx)
	items, err := r.ReportRepo.GetHighRiskVendors(ctx, createdBy)
	if err != nil {
		return nil, err
	}
	result := make([]*model.HighRiskVendor, len(items))
	for i, item := range items {
		var score *float64
		if item.OverallRiskScore != 0 {
			score = &item.OverallRiskScore
		}
		var assessmentDate, assessStatus *string
		if item.LatestAssessment != "" {
			assessmentDate = &item.LatestAssessment
		}
		if item.AssessmentStatus != "" {
			assessStatus = &item.AssessmentStatus
		}
		result[i] = &model.HighRiskVendor{
			Code:                item.Code,
			Name:                item.Name,
			Category:            item.Category,
			RiskLevel:           item.RiskLevel,
			OverallRiskScore:    score,
			LatestAssessment:    assessmentDate,
			AssessmentStatus:    assessStatus,
			ExpiringContracts30: &item.ExpiringContracts30,
		}
	}
	return result, nil
}

// ExpiringContractsReport is the resolver for the expiringContractsReport field.
func (r *queryResolver) ExpiringContractsReport(ctx context.Context) ([]*model.ExpiringContract, error) {
	createdBy := getDepartmentManagerID(ctx)
	items, err := r.ReportRepo.GetExpiringContractsReport(ctx, createdBy)
	if err != nil {
		return nil, err
	}
	result := make([]*model.ExpiringContract, len(items))
	for i, item := range items {
		result[i] = &model.ExpiringContract{
			Code:           item.Code,
			VendorName:     item.VendorName,
			VendorCode:     item.VendorCode,
			ContractNumber: item.ContractNumber,
			EndDate:        item.EndDate,
			DaysRemaining:  item.DaysRemaining,
			RenewalStatus:  item.RenewalStatus,
			ContractValue:  &item.ContractValue,
		}
	}
	return result, nil
}

// ComplianceSummaryReport is the resolver for the complianceSummaryReport field.
func (r *queryResolver) ComplianceSummaryReport(ctx context.Context) ([]*model.ComplianceSummaryItem, error) {
	createdBy := getDepartmentManagerID(ctx)
	items, err := r.ReportRepo.GetComplianceSummary(ctx, createdBy)
	if err != nil {
		return nil, err
	}
	result := make([]*model.ComplianceSummaryItem, len(items))
	for i, item := range items {
		result[i] = &model.ComplianceSummaryItem{
			CertificationType: item.CertificationType,
			Approved:          item.Approved,
			Pending:           item.Pending,
			Expired:           item.Expired,
			Total:             item.Total,
		}
	}
	return result, nil
}

// TimeSeriesReport is the resolver for the timeSeriesReport field.
func (r *queryResolver) TimeSeriesReport(ctx context.Context) (*model.TimeSeries, error) {
	createdBy := getDepartmentManagerID(ctx)
	ts, err := r.ReportRepo.GetTimeSeries(ctx, createdBy)
	if err != nil {
		return nil, err
	}
	vendors := make([]*model.TimeSeriesPoint, len(ts.Vendors))
	for i, p := range ts.Vendors {
		vendors[i] = &model.TimeSeriesPoint{Date: p.Date, Count: p.Count}
	}
	risks := make([]*model.TimeSeriesPoint, len(ts.RiskAssessments))
	for i, p := range ts.RiskAssessments {
		risks[i] = &model.TimeSeriesPoint{Date: p.Date, Count: p.Count}
	}
	comps := make([]*model.TimeSeriesPoint, len(ts.Compliance))
	for i, p := range ts.Compliance {
		comps[i] = &model.TimeSeriesPoint{Date: p.Date, Count: p.Count}
	}
	return &model.TimeSeries{
		Vendors:         vendors,
		RiskAssessments: risks,
		Compliance:      comps,
	}, nil
}
