package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.92

import (
	"context"

	"github.com/google/uuid"
	"github.com/uswuth/vytora-backend/internal/entity/risk_assessment"
	"github.com/uswuth/vytora-backend/internal/graphql/model"
)

// CreateRiskAssessment is the resolver for the createRiskAssessment field.
func (r *mutationResolver) CreateRiskAssessment(ctx context.Context, input model.CreateRiskAssessmentInput) (*model.RiskAssessment, error) {
	v, err := r.VendorRepo.FindByCode(ctx, input.VendorCode)
	if err != nil {
		return nil, &NotFoundError{Resource: "vendor"}
	}
	code, err := r.SeqService.NextCode(ctx, "risk_assessment")
	if err != nil {
		return nil, err
	}
	claims, _ := GetClaims(ctx)
	assessorID, err := uuid.Parse(claims.UserID)
	if err != nil {
		return nil, &UnauthorizedError{}
	}
	ra := &risk_assessment.RiskAssessment{
		Code:                 code,
		VendorID:             v.ID,
		VendorCode:           v.Code,
		AssessmentDate:       input.AssessmentDate,
		AssessorID:           &assessorID,
		OverallRiskScore:     input.OverallRiskScore,
		RiskLevel:            string(input.RiskLevel),
		SecurityRiskScore:    input.SecurityRiskScore,
		FinancialRiskScore:   input.FinancialRiskScore,
		OperationalRiskScore: input.OperationalRiskScore,
		LegalRiskScore:       input.LegalRiskScore,
		Status:               "Draft",
		Notes:                derefString(input.Notes),
	}
	if err := r.RiskAssessmentRepo.Create(ctx, ra); err != nil {
		return nil, err
	}
	_ = r.AuditLogger.LogCreateSimple(ctx, "risk_assessments", ra.ID, ra.Code, assessorID)
	return mapRiskAssessmentToGraphQL(ra), nil
}

// UpdateRiskAssessment is the resolver for the updateRiskAssessment field.
func (r *mutationResolver) UpdateRiskAssessment(ctx context.Context, code string, input model.UpdateRiskAssessmentInput) (*model.RiskAssessment, error) {
	ra, err := r.RiskAssessmentRepo.FindByCode(ctx, code)
	if err != nil {
		return nil, &NotFoundError{Resource: "risk assessment"}
	}
	claims, _ := GetClaims(ctx)
	assessorID, _ := uuid.Parse(claims.UserID)
	ra.AssessmentDate = input.AssessmentDate
	ra.AssessorID = &assessorID
	ra.OverallRiskScore = input.OverallRiskScore
	ra.RiskLevel = string(input.RiskLevel)
	ra.SecurityRiskScore = input.SecurityRiskScore
	ra.FinancialRiskScore = input.FinancialRiskScore
	ra.OperationalRiskScore = input.OperationalRiskScore
	ra.LegalRiskScore = input.LegalRiskScore
	ra.Status = string(input.Status)
	ra.Notes = derefString(input.Notes)

	if err := r.RiskAssessmentRepo.Update(ctx, ra); err != nil {
		return nil, err
	}
	_ = r.AuditLogger.LogCreateSimple(ctx, "risk_assessments", ra.ID, ra.Code, assessorID)
	return mapRiskAssessmentToGraphQL(ra), nil
}

// DeleteRiskAssessment is the resolver for the deleteRiskAssessment field.
func (r *mutationResolver) DeleteRiskAssessment(ctx context.Context, code string) (bool, error) {
	ra, err := r.RiskAssessmentRepo.FindByCode(ctx, code)
	if err != nil {
		return false, &NotFoundError{Resource: "risk assessment"}
	}
	if err := r.RiskAssessmentRepo.Delete(ctx, code); err != nil {
		return false, err
	}
	claims, _ := GetClaims(ctx)
	changedBy, _ := uuid.Parse(claims.UserID)
	_ = r.AuditLogger.LogDeleteSimple(ctx, "risk_assessments", ra.ID, ra.Code, changedBy)
	return true, nil
}

// ApproveRiskAssessment is the resolver for the approveRiskAssessment field.
func (r *mutationResolver) ApproveRiskAssessment(ctx context.Context, code string) (bool, error) {
	ra, err := r.RiskAssessmentRepo.FindByCode(ctx, code)
	if err != nil {
		return false, &NotFoundError{Resource: "risk assessment"}
	}
	oldStatus := ra.Status
	ra.Status = "Approved"
	if err := r.RiskAssessmentRepo.Update(ctx, ra); err != nil {
		return false, err
	}
	claims, _ := GetClaims(ctx)
	changedBy, _ := uuid.Parse(claims.UserID)
	_ = r.AuditLogger.LogUpdateField(ctx, "risk_assessments", ra.ID, "status", oldStatus, "Approved", changedBy)
	return true, nil
}

// RiskAssessments is the resolver for the riskAssessments field.
func (r *queryResolver) RiskAssessments(ctx context.Context, vendorCode *string, riskLevel *model.RiskLevel, status *model.AssessmentStatus, limit *int, offset *int) ([]*model.RiskAssessment, error) {
	params := risk_assessment.ListParams{}
	if vendorCode != nil {
		params.VendorCode = *vendorCode
	}
	if riskLevel != nil {
		params.RiskLevel = string(*riskLevel)
	}
	if status != nil {
		params.Status = string(*status)
	}
	if limit != nil {
		params.Limit = *limit
	}
	if offset != nil {
		params.Offset = *offset
	}
	assessments, _, err := r.RiskAssessmentRepo.ListAll(ctx, params)
	if err != nil {
		return nil, err
	}
	result := make([]*model.RiskAssessment, len(assessments))
	for i, ra := range assessments {
		result[i] = mapRiskAssessmentToGraphQL(&ra)
	}
	return result, nil
}

// RiskAssessment is the resolver for the riskAssessment field.
func (r *queryResolver) RiskAssessment(ctx context.Context, code string) (*model.RiskAssessment, error) {
	ra, err := r.RiskAssessmentRepo.FindByCode(ctx, code)
	if err != nil {
		return nil, &NotFoundError{Resource: "risk assessment"}
	}
	return mapRiskAssessmentToGraphQL(ra), nil
}
