package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.92

import (
	"context"

	"github.com/google/uuid"
	"github.com/uswuth/vytora-backend/internal/entity/user"
	"github.com/uswuth/vytora-backend/internal/graphql/model"
	"golang.org/x/crypto/bcrypt"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*model.LoginResponse, error) {
	u, err := r.UserRepo.FindByEmail(ctx, email)
	if err != nil {
		return nil, &InvalidCredentialsError{}
	}
	if err := bcrypt.CompareHashAndPassword([]byte(u.PasswordHash), []byte(password)); err != nil {
		return nil, &InvalidCredentialsError{}
	}
	if !u.IsActive {
		return nil, &AccountDeactivatedError{}
	}
	token, err := r.JWTService.GenerateToken(u)
	if err != nil {
		return nil, err
	}
	return &model.LoginResponse{
		Token: token,
		User:  mapUserToGraphQL(u),
	}, nil
}

// ExtendSession is the resolver for the extendSession field.
func (r *mutationResolver) ExtendSession(ctx context.Context) (*model.LoginResponse, error) {
	// Retrieve the raw token from context (set by auth middleware)
	rawToken, ok := GetRawToken(ctx)
	if !ok {
		return nil, &UnauthorizedError{}
	}
	newToken, ttl, err := r.JWTService.ExtendToken(rawToken)
	if err != nil {
		return nil, &UnauthorizedError{}
	}
	_ = ttl // ttl is in seconds; could be added to response if needed
	claims, err := r.JWTService.ValidateToken(newToken)
	if err != nil {
		return nil, err
	}
	uid, _ := uuid.Parse(claims.UserID)
	u, err := r.UserRepo.FindByID(ctx, uid.String())
	if err != nil {
		return nil, err
	}
	return &model.LoginResponse{
		Token: newToken,
		User:  mapUserToGraphQL(u),
	}, nil
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.User, error) {
	code, err := r.SeqService.NextCode(ctx, "user")
	if err != nil {
		return nil, err
	}
	hash, err := bcrypt.GenerateFromPassword([]byte(input.Password), bcrypt.DefaultCost)
	if err != nil {
		return nil, err
	}
	u := &user.User{
		Code:         code,
		Email:        input.Email,
		PasswordHash: string(hash),
		FullName:     input.FullName,
		Role:         string(input.Role),
		IsActive:     true,
	}
	if err := r.UserRepo.Create(ctx, u); err != nil {
		return nil, err
	}
	return mapUserToGraphQL(u), nil
}

// UpdateUserRole is the resolver for the updateUserRole field.
func (r *mutationResolver) UpdateUserRole(ctx context.Context, id string, input model.UpdateRoleInput) (bool, error) {
	err := r.UserRepo.UpdateRole(ctx, id, string(input.Role))
	return err == nil, err
}

// DeactivateUser is the resolver for the deactivateUser field.
func (r *mutationResolver) DeactivateUser(ctx context.Context, id string) (bool, error) {
	err := r.UserRepo.SetActive(ctx, id, false)
	return err == nil, err
}

// ActivateUser is the resolver for the activateUser field.
func (r *mutationResolver) ActivateUser(ctx context.Context, id string) (bool, error) {
	err := r.UserRepo.SetActive(ctx, id, true)
	return err == nil, err
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	claims, _ := GetClaims(ctx)
	if claims == nil {
		return nil, &UnauthorizedError{}
	}
	uid, err := uuid.Parse(claims.UserID)
	if err != nil {
		return nil, err
	}
	u, err := r.UserRepo.FindByID(ctx, uid.String())
	if err != nil {
		return nil, err
	}
	return mapUserToGraphQL(u), nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	users, err := r.UserRepo.ListAll(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*model.User, len(users))
	for i, u := range users {
		result[i] = mapUserToGraphQL(&u)
	}
	return result, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	u, err := r.UserRepo.FindByID(ctx, id)
	if err != nil {
		return nil, err
	}
	return mapUserToGraphQL(u), nil
}
