package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.92

import (
	"context"

	"github.com/google/uuid"
	"github.com/uswuth/vytora-backend/internal/entity/vendor"
	"github.com/uswuth/vytora-backend/internal/graphql/model"
)

// CreateVendor is the resolver for the createVendor field.
func (r *mutationResolver) CreateVendor(ctx context.Context, input model.CreateVendorInput) (*model.Vendor, error) {
	// Validate category active
	if input.Category != "" {
		active, err := r.CategoryRepo.IsActive(ctx, input.Category)
		if err != nil || !active {
			return nil, &ValidationError{Message: "category not found or inactive"}
		}
	}

	code, err := r.SeqService.NextCode(ctx, "vendor")
	if err != nil {
		return nil, err
	}

	claims, _ := GetClaims(ctx)
	createdBy, err := uuid.Parse(claims.UserID)
	if err != nil {
		return nil, &UnauthorizedError{}
	}

	v := &vendor.Vendor{
		Code:          code,
		Name:          input.Name,
		Category:      input.Category,
		ContactPerson: derefString(input.ContactPerson),
		ContactEmail:  derefString(input.ContactEmail),
		Country:       derefString(input.Country),
		RiskLevel:     string(input.RiskLevel),
		Status:        "Draft",
		CreatedBy:     createdBy,
	}

	if err := r.VendorRepo.Create(ctx, v); err != nil {
		return nil, err
	}

	// Log audit
	if err := r.AuditLogger.LogCreate(ctx, "vendors", v.ID, createdBy, v); err != nil {
		// Log but don't fail
	}

	return mapVendorToGraphQL(v), nil
}

// UpdateVendor is the resolver for the updateVendor field.
func (r *mutationResolver) UpdateVendor(ctx context.Context, code string, input model.UpdateVendorInput) (*model.Vendor, error) {
	existing, err := r.VendorRepo.FindByCode(ctx, code)
	if err != nil {
		return nil, &NotFoundError{Resource: "vendor"}
	}

	if input.Category != "" {
		active, err := r.CategoryRepo.IsActive(ctx, input.Category)
		if err != nil || !active {
			return nil, &ValidationError{Message: "category not found or inactive"}
		}
	}

	existing.Name = input.Name
	existing.Category = input.Category
	existing.ContactPerson = derefString(input.ContactPerson)
	existing.ContactEmail = derefString(input.ContactEmail)
	existing.Country = derefString(input.Country)
	existing.RiskLevel = string(input.RiskLevel)
	existing.Status = string(input.Status)

	if err := r.VendorRepo.Update(ctx, existing); err != nil {
		return nil, err
	}

	claims, _ := GetClaims(ctx)
	changedBy, _ := uuid.Parse(claims.UserID)
	if err := r.AuditLogger.LogCreate(ctx, "vendors", existing.ID, changedBy, existing); err != nil {
		// log
	}

	return mapVendorToGraphQL(existing), nil
}

// DeleteVendor is the resolver for the deleteVendor field.
func (r *mutationResolver) DeleteVendor(ctx context.Context, code string) (bool, error) {
	v, err := r.VendorRepo.FindByCode(ctx, code)
	if err != nil {
		return false, &NotFoundError{Resource: "vendor"}
	}
	if err := r.VendorRepo.Delete(ctx, code); err != nil {
		return false, err
	}
	claims, _ := GetClaims(ctx)
	changedBy, _ := uuid.Parse(claims.UserID)
	_ = r.AuditLogger.LogDelete(ctx, "vendors", v.ID, v, changedBy)
	return true, nil
}

// SubmitVendor is the resolver for the submitVendor field.
func (r *mutationResolver) SubmitVendor(ctx context.Context, code string) (bool, error) {
	v, err := r.VendorRepo.FindByCode(ctx, code)
	if err != nil {
		return false, &NotFoundError{Resource: "vendor"}
	}
	if v.Status != "Draft" {
		return false, &ValidationError{Message: "vendor must be in Draft status"}
	}
	if err := r.VendorRepo.UpdateStatus(ctx, code, "Submitted"); err != nil {
		return false, err
	}
	claims, _ := GetClaims(ctx)
	changedBy, _ := uuid.Parse(claims.UserID)
	_ = r.AuditLogger.LogUpdateField(ctx, "vendors", v.ID, "status", "Draft", "Submitted", changedBy)
	return true, nil
}

// ReviewVendorRisk is the resolver for the reviewVendorRisk field.
func (r *mutationResolver) ReviewVendorRisk(ctx context.Context, code string) (bool, error) {
	v, err := r.VendorRepo.FindByCode(ctx, code)
	if err != nil {
		return false, &NotFoundError{Resource: "vendor"}
	}
	if v.Status != "Submitted" {
		return false, &ValidationError{Message: "vendor must be in Submitted status"}
	}
	if err := r.VendorRepo.UpdateStatus(ctx, code, "RiskReview"); err != nil {
		return false, err
	}
	claims, _ := GetClaims(ctx)
	changedBy, _ := uuid.Parse(claims.UserID)
	_ = r.AuditLogger.LogUpdateField(ctx, "vendors", v.ID, "status", "Submitted", "RiskReview", changedBy)
	return true, nil
}

// ReviewVendorCompliance is the resolver for the reviewVendorCompliance field.
func (r *mutationResolver) ReviewVendorCompliance(ctx context.Context, code string) (bool, error) {
	v, err := r.VendorRepo.FindByCode(ctx, code)
	if err != nil {
		return false, &NotFoundError{Resource: "vendor"}
	}
	if v.Status != "RiskReview" {
		return false, &ValidationError{Message: "vendor must be in RiskReview status"}
	}
	if err := r.VendorRepo.UpdateStatus(ctx, code, "ComplianceReview"); err != nil {
		return false, err
	}
	claims, _ := GetClaims(ctx)
	changedBy, _ := uuid.Parse(claims.UserID)
	_ = r.AuditLogger.LogUpdateField(ctx, "vendors", v.ID, "status", "RiskReview", "ComplianceReview", changedBy)
	return true, nil
}

// ApproveVendor is the resolver for the approveVendor field.
func (r *mutationResolver) ApproveVendor(ctx context.Context, code string) (bool, error) {
	v, err := r.VendorRepo.FindByCode(ctx, code)
	if err != nil {
		return false, &NotFoundError{Resource: "vendor"}
	}
	if v.Status != "ComplianceReview" {
		return false, &ValidationError{Message: "vendor must be in ComplianceReview status"}
	}
	if err := r.VendorRepo.UpdateStatus(ctx, code, "Approved"); err != nil {
		return false, err
	}
	claims, _ := GetClaims(ctx)
	changedBy, _ := uuid.Parse(claims.UserID)
	_ = r.AuditLogger.LogUpdateField(ctx, "vendors", v.ID, "status", "ComplianceReview", "Approved", changedBy)
	return true, nil
}

// RejectVendor is the resolver for the rejectVendor field.
func (r *mutationResolver) RejectVendor(ctx context.Context, code string) (bool, error) {
	v, err := r.VendorRepo.FindByCode(ctx, code)
	if err != nil {
		return false, &NotFoundError{Resource: "vendor"}
	}
	if v.Status == "Rejected" || v.Status == "Approved" {
		return false, &ValidationError{Message: "vendor cannot be rejected from current status"}
	}
	oldStatus := v.Status
	if err := r.VendorRepo.UpdateStatus(ctx, code, "Rejected"); err != nil {
		return false, err
	}
	claims, _ := GetClaims(ctx)
	changedBy, _ := uuid.Parse(claims.UserID)
	_ = r.AuditLogger.LogUpdateField(ctx, "vendors", v.ID, "status", oldStatus, "Rejected", changedBy)
	return true, nil
}

// Vendors is the resolver for the vendors field.
func (r *queryResolver) Vendors(ctx context.Context, filter *model.VendorListFilter, limit *int, offset *int, sortBy *string, sortOrder *string) (*model.VendorList, error) {
	params := vendor.ListParams{}
	if filter != nil {
		if filter.Search != nil {
			params.Search = *filter.Search
		}
		if filter.Category != nil {
			params.Category = *filter.Category
		}
		if filter.RiskLevel != nil {
			params.RiskLevel = string(*filter.RiskLevel)
		}
		if filter.Status != nil {
			params.Status = string(*filter.Status)
		}
		if filter.Country != nil {
			params.Country = *filter.Country
		}
		if filter.CreatedBy != nil {
			uid, err := uuid.Parse(*filter.CreatedBy)
			if err == nil {
				params.CreatedBy = &uid
			}
		}
	}
	if limit != nil {
		params.Limit = *limit
	}
	if offset != nil {
		params.Offset = *offset
	}
	if sortBy != nil {
		params.SortBy = *sortBy
	}
	if sortOrder != nil {
		params.SortOrder = *sortOrder
	}

	// Department managers see only vendors they created
	claims, _ := GetClaims(ctx)
	if claims != nil && claims.Role == "department_manager" {
		uid, _ := uuid.Parse(claims.UserID)
		params.CreatedBy = &uid
	}

	vendors, total, err := r.VendorRepo.List(ctx, params)
	if err != nil {
		return nil, err
	}
	gqlVendors := make([]*model.Vendor, len(vendors))
	for i, v := range vendors {
		gqlVendors[i] = mapVendorToGraphQL(&v)
	}
	return &model.VendorList{Data: gqlVendors, Total: total}, nil
}

// Vendor is the resolver for the vendor field.
func (r *queryResolver) Vendor(ctx context.Context, code string) (*model.Vendor, error) {
	v, err := r.VendorRepo.FindByCode(ctx, code)
	if err != nil {
		return nil, &NotFoundError{Resource: "vendor"}
	}
	return mapVendorToGraphQL(v), nil
}
